### ISSUE TITLE
PET method?

### ISSUE THREAD

**Issue by towlere** [mines-ciroh/clear_creek_demo#6]
Can you add this init_config file to your repo so I can see what PET method you are using?
https://github.com/mines-ciroh/clear_creek_demo/blob/cdfe25c49eb66e9b697da3a56be4a8c2092cc5ac/config/06719505/realization_file.06719505.nom.json#L57

**Comment by andywood** [comment]
From these paths, it looks like this json file still needs updating.  I reorganized the repo structure so that it doesn't include 'SHARP'.  we will add this file.

**Comment by joshsturtevant** [comment]
@towlere just seeing this now! I've added those init_config files here: https://github.com/mines-ciroh/clear_creek_demo/tree/main/inputs/settings/06719505/pet

I will also update the realization file examples so they are pointing to the corresponding directories within this repo
